### ISSUE TITLE
A tiny tool for sign/check from terminal

### ISSUE THREAD

**Issue by malukenho** [Roave/Signature#7]
Would it be good if we provide some kind of "write signature to file" functionality?
What you guys think about a tiny tool for signing/checking files from terminal?

**Comment by asgrim** [comment]
I think most use cases will be programmatic rather than using from a CLI (such as Better Reflection, Proxy Manager etc.)

**Comment by Ocramius** [comment]
Don't think this is the right use-case scenario either: useful, yes, but tools like `git` already support signed tags and commits as alternative.

Closing as `wontfix`
